<a href="https://colab.research.google.com/github/Gopisetti9Bhargav/403/blob/main/Data_Science_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 1 :03-07-2025

In [ ]:
#Defauklt Indexing
a="Hello Bhargav"
print(a)
print(a[::-1]) #reverse string
print(a[::2]) #even string
print(a[1::2]) #odd string
print(a[6:13])
print(a[-1:-9:-1])
print(a[-1:-13:-2])

Hello Bhargav
vagrahB olleH
HloBagv
el hra
Bhargav
vagrahB 
vgaBol


In [ ]:
# String Methods
# print(dir(a))
# print(dir(1))
a="Hello Hyderabad"
print(a.capitalize()) #1st letter capital
print(a.upper()) #all upper
print(a.lower()) #all lower
print(a.title()) #1st capital all strings
print(a.replace('Hyderabad','Vijayawada')) #replace string
print(a.strip())
print(a.lstrip()) #prints l to r
print(a.rstrip()) #prints r to l
print(a.find('H')) #finds index value
print(a.index("a")) #find index
print(a.find('j')) #if letter is not there it gives -1 in find method
# print(a.index('w')) #if letter is not there it gives value error in index method

In [ ]:
b="VijAwADa"
print(b.swapcase()) #reverse upper to lower vise versa
print(b.zfill(13)) #create string of derived length

vIJaWadA
00000VijAwADa


In [ ]:
# String Formating
age=10
inp="My name is Bhargav and I am {} years old"
print(inp.format(age))
# Method 2
age=21
inp="My age is {}".format(age)
print(inp)
# Method 3
item=input("Enter Food Item")
price=int(input("Enter Price"))
qua=int(input("Enter quantity"))
print(f"Your {item} for {qua} is {price} and total is {price*qua}")

My name is Bhargav and I am 10 years old
My age is 21
Enter Food ItemIdly
Enter Price30
Enter quantity2
Your Idly for 2 is 30 and total is 60


In [ ]:
# Escape Characters
a="Hello \"Bhargav\" Naidu" #Used to use illegal orguments
print(a)
b="Hello 'Bhargav' Naidu"
print(b)

Hello "Bhargav" Naidu
Hello 'Bhargav' Naidu


**08-07-2025**

In [ ]:
# Nested Conditions
# Used to check multiple conditions
a=35
if a>10:
  print("a is greater than 10")
  if a>20:
    print("a is greater than 20")
  else:
    print("a is less than 20")
  if a>30:
    print("a is greater than 30")
  else:
    print("a is less than 30")
  if a>40:
    print("a is greater than 40")
  else:
    print("a is less than 40")
else:
  print("a is less than \"10\"")


a is greater than 10
a is greater than 20
a is greater than 30
a is less than 40


In [ ]:
# Terinary operators
# Used to check 2 conditions in simple form either true or false in a single line we use terinary operator
age=int(input("Enter your age:"))
check= "Eligible" if age>=18 else "Not Eligible"
print(check)
# syntax: "True" ,<space> condition <space> else <space> "False"

Enter your age:17
Not Eligible


In [ ]:
# PASS
# null place holder
# used when code is incomplete and not to raise errors
a=100
if a>10:
  pass

11-07-2025

In [ ]:
# Collection --
# 1.Homogenoud Data --(Single Data Type)
# 2.Hetrogenous Data --(Multiple Data type)
# Collections is also know as iterables (List, Tuple, Dictionary, Set)

In [ ]:
# List
# [Ordered , Mutable & allows duplicate data ]
l1=['apple','kiwi','pineapple','banana','apple','watermelon','apple','orange']
print(type(l1))
print(l1)
print(len(l1))
print(l1[2:5])

<class 'list'>
['apple', 'kiwi', 'pineapple', 'banana', 'apple', 'watermelon', 'apple', 'orange']
8
['pineapple', 'banana', 'apple']


In [ ]:
print(l1[0:8:2]) #even index[star:end:step]
print(l1[2:len(l1):2])

['apple', 'pineapple', 'apple', 'apple']
['pineapple', 'apple', 'apple']


**14-07-2025**

In [ ]:
a="Hello World!"
print(dir(a)) #It checks what action we perform on a string

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [ ]:
print(a.replace("Hello","Universe")) #Replace the values

Universe World!


In [ ]:
print(a.zfill(16)) #fills the value for desired valus

0000Hello World!


In [ ]:
# List allows Duplicate data


In [ ]:
l11=["apple","banana","orange","grapes"]
print(l11[::2])

['apple', 'orange']


In [ ]:
print(l11[-1::-1])

['grapes', 'orange', 'banana', 'apple']


In [ ]:
# List has 3 properties
# 1.Replace or swap the elements
# 2.Add the new items to existing list
# 3.Remove the items from the list

In [ ]:
l3=['Python','Java','Js','C++','c']
print(l3)
l3[2]="Java Script" #In Data Structure there is no replace methos
print(l3)


['Python', 'Java', 'Js', 'C++', 'c']
['Python', 'Java', 'Java Script', 'C++', 'c']


In [ ]:
l3[0:2]="Sql","Mysql","Nosql"
print(l3)

['Sql', 'Mysql', 'Nosql', 'Java Script', 'C++', 'c']


In [ ]:
# Add items to existing list
l4=['Sql', 'Mysql', 'Nosql', 'Java Script', 'C++', 'c']
print(l4)

['Sql', 'Mysql', 'Nosql', 'Java Script', 'C++', 'c']


In [ ]:
l4.append("Python") #append adds only one item
l4.insert(3,"Java")

In [ ]:
print(l4)

['Sql', 'Mysql', 'Nosql', 'Java', 'Java Script', 'C++', 'c', 'Python', 'Python', '.net', 'css', 'html']


In [ ]:
# Extend() used to add multiple elements
l5=[".net","css","html"]
l4.extend(l5)
print(l4)

['Sql', 'Mysql', 'Nosql', 'Java', 'Java Script', 'C++', 'c', 'Python', 'Python', '.net', 'css', 'html', '.net', 'css', 'html', '.net', 'css', 'html']


In [ ]:
print(l5)

['.net', 'css', 'html']


In [ ]:
l4.extend(l5)

In [ ]:
# pop() used to delete the elements in a list from the last
l6=[1,2,3,4,5,6,7]
l6.pop()
print(l6)

[1, 2, 3, 4, 5, 6]


In [ ]:
# remove()
l6.remove(2)
print(l6)

[1, 3, 4, 5, 6]


In [ ]:
# del [] using index
ll=["Java","Python","Css","Html",1 ,2,3,4]
del ll[1:]
print(ll)

['Java']


In [ ]:
# clear()
ll.clear()
print(ll)

[]


In [ ]:
# sorting a list
a=["apple","Apple",'Banana','banana','Grapes','orange','Lemon']
a.sort() #In asc order A to a
print(a)

['Apple', 'Banana', 'Grapes', 'Lemon', 'apple', 'banana', 'orange']


In [ ]:
# In desc order a to A
a.sort(reverse=True)
print(a)

['orange', 'banana', 'apple', 'Lemon', 'Grapes', 'Banana', 'Apple']


In [ ]:
# Tuple
# tuple()
# tuple is ordered, immutable, and allows duplicates

In [ ]:
t1=(1,2,3,4,5,6,1,2,3,4,5)
print(len(t1))
print(type(t1))
print(t1)
print(t1[::2])

11
<class 'tuple'>
(1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5)
(1, 3, 5, 1, 3, 5)


In [ ]:
# Immutable means we cannot perform any crud operations

**15-07-2025**

In [ ]:
# set{}
# Set is unordered, immutable

In [ ]:
s1={'apple','mango','banana','grapes'}
print(s1)
print(type(s1))

{'grapes', 'banana', 'apple', 'mango'}
<class 'set'>


In [ ]:
s2={'apple','mango','banana','pineapple','orange'}
print(s2)

{'banana', 'apple', 'orange', 'mango', 'pineapple'}


In [ ]:
# Adding menthods in set
# add
s2.add('grapes')
print(s2)  #we only add single items using this method

{'banana', 'apple', 'grapes', 'orange', 'mango', 'pineapple'}


In [ ]:
# update()
s3={1,2,3,4,5,6}
s2.update(s3)
print(s2)

{1, 2, 3, 4, 5, 6, 'grapes', 'mango', 'banana', 'apple', 'orange', 'pineapple'}


In [ ]:
# pop()
s2.pop()
print(s2)

{2, 3, 4, 5, 6, 'grapes', 'mango', 'banana', 'apple', 'orange', 'pineapple'}


In [ ]:
# remove() for elements
s2.remove('mango')
print(s2)

{2, 3, 4, 5, 6, 'grapes', 'banana', 'apple', 'orange', 'pineapple'}


In [ ]:
# # discard()
s2.discard(3)
print(s2)
# In remove method if element is not exist it raise error,
# where as in discard method it doesnt raise error

{2, 4, 5, 6, 'grapes', 'banana', 'apple', 'orange', 'pineapple'}


In [ ]:
# clear()
print(s2.clear())

None


In [ ]:
# sets are faster then list and tuple because set is unordered and immutable

In [ ]:
s1={'a','b','c''d'}
s2={'e','d','f','g'}
print(s1.union(s2))

{'f', 'cd', 'e', 'a', 'd', 'b', 'g'}


In [ ]:
print(s1.intersection(s2))

set()


In [ ]:
# Dictionary{}
# dictionary is unordered, mutable and wont allows duplicate data
# {key:value}

In [ ]:
d1={'name':'MET',
    'course':'Ds/Da/Gen',
    'duration':'4 months',
    'course':'Python',
    'topics':['numpy','pandas','seaborn']}
print(d1)
print(len(d1))

{'name': 'MET', 'course': 'Python', 'duration': '4 months', 'topics': ['numpy', 'pandas', 'seaborn']}
4


In [ ]:
# Dictionary is mutable
d1['address']='Hyderabad'
print(d1)

{'name': 'MET', 'course': 'Python', 'duration': '4 months', 'topics': ['numpy', 'pandas', 'seaborn'], 'address': 'Hyderabad'}


In [ ]:
d1['course']='python'
print(d1)

{'name': 'MET', 'course': 'python', 'duration': '4 months', 'topics': ['numpy', 'pandas', 'seaborn'], 'address': 'Hyderabad'}


In [ ]:
d2={
    'other course':['js','rs','html']
}
d1.update(d2)
print(d1)

{'name': 'MET', 'course': 'python', 'duration': '4 months', 'topics': ['numpy', 'pandas', 'seaborn'], 'address': 'Hyderabad', 'other course': ['js', 'rs', 'html']}


In [ ]:
d1['topics'][-1]='ML'
d1['topics'][-2]='numpy'
print(d1)

{'name': 'MET', 'course': 'python', 'duration': '4 months', 'topics': ['ML', 'numpy', 'ML'], 'address': 'Hyderabad', 'other course': ['js', 'rs', 'html']}


In [ ]:
# pop() remove items
d1.pop('other course')
print(d1)

{'name': 'MET', 'course': 'python', 'duration': '4 months', 'topics': ['ML', 'numpy', 'ML'], 'address': 'Hyderabad'}


In [ ]:
# popitem():default removes last item and return the removed item
d1.popitem()
print(d1)

{'name': 'MET', 'course': 'python', 'duration': '4 months', 'topics': ['ML', 'numpy', 'ML']}


**16-07-2025**

In [ ]:
# function
# Functions are used to avoid duplicates codes (Loops also)
# Function is a block of code which can be executed when you call it.

In [ ]:
def f1():
  print("Hello world!")
f1()

Hello world!


In [ ]:
# Parameter
# when we define a function we create a variable which is known as parameter
def f2(name):
  print('Hello',name)
# Argument
# when we call function we pass some values is known as arguments
f2('Medha')
# Expression means block of code to execute

Hello Medha


In [ ]:
# we can pass n number of parameters and arguments
def details(name,age,gender,contact):
  print("Hello check details",name,age,gender,contact)
details("Bhargav",'21','M','9247275933')
# No of arguments=No of parameter

Hello check details Bhargav 21 M 9247275933


In [ ]:
# create a function to check a number is even or add
def check_num(num):
  if num%2==0:
    print("Even")
  else:
    print("Odd")
check_num(256150178)

Even


In [ ]:
# create a function to sum of numbers in a list
l=[1,2,3,4,5,6,7,8,9]
sum=0
for i in l:
  sum+=i
print(sum)

45


In [ ]:
# create a function call total_of_num to print sum of numbers in the given list
def total_of_num(l):
  sum=0
  for i in l:
    sum+=i
  print(sum)
total_of_num([1,2,3,4,5,6,7,8,9,10])

55


In [ ]:
total_of_num([1,2,3,4,5])

15


In [ ]:
# Dont know how many parameters i need to pass but function has to print all the information
def details(**name):
  print(name)
details(name="Bhargav",age=21,gender="M")

{'name': 'Bhargav', 'age': 21, 'gender': 'M'}


In [ ]:
def topics(*name):
  print(name)
topics("Python","Java","Sql","Html")

('Python', 'Java', 'Sql', 'Html')


In [ ]:
# from ast import arguments
# 1. ** ---> KWARGS --> Keyword arbitary arguments
#         uses when we dont know how many parameters need to pass
#         The defaukt data type is Dictionary
# 2. * --> ARGS --> Arbitary arguments
#         When we dont know the number of arguments need to pass
#         The default data type Tuple

In [ ]:
a=set([1,2,3,4,5,6])
print(a)

{1, 2, 3, 4, 5, 6}


In [ ]:
# Create a function to print sum of arguments
def total_of_nums(*l):
  sum=0
  for i in l:
    sum+=i
  print(sum)
total_of_nums(20,30,40,50,60,70)

270


In [ ]:
# create a function where it can concatenate the words and form a sentance
def concat(**words):
  result=""
  for i in words.values():
    result=result+i
  print(result)
concat(a="Python ",b="is ",c="Programing language.")

Python is Programing language.


In [ ]:
# return--> send back the values to the caller
# note --> when we use the return keyword instead of print call function with rint statement
def f1(a,b):
  return a+b
print(f1(10,44))

54


**17-07-2025**

In [ ]:
# List comprehension
# LC offers smaller line of code where a new list can be created from the existing list.
a=['apple','banana','pineapple','orange','mango','watermelon']
# program to print 'e'and store in it
new=[]
for i in a:
  if 'e' in i:
    new.append(i)
print(new)

['apple', 'pineapple', 'orange', 'watermelon']


In [ ]:
def check_fruit(a):
  new=[]
  for i in a:
    if 'e' in i:
      new.append(i)
  return new
  # call function
a=['kiwi','apple','grapes','mango','pineapple']
print(check_fruit(a))

['apple', 'grapes', 'pineapple']


In [ ]:
# syntax : [item for item in collection <space> apply condition]
a=['apple','banana','pineapple','orange','mango','watermelon']
new=[i for i in a if 'e' in i]
print(new)

['apple', 'pineapple', 'orange', 'watermelon']


In [ ]:
# write program to print a range of even numbers from 1 to 40 and store it in a list
new=[]
for i in range(1,41):
  if i%2==0:
    new.append(i)
print(new)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]


In [ ]:
# create by using the LC
new=[i for i in range(1,41) if i%2==0]
print(new)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]


In [ ]:
# write a program to convert all the items in a list to uppercase and store it in a new list
l=['apple','banana','pineapple','orange','mango','watermelon']
n=[]
for i in l:
  n.append(i.upper())
print(n)

['APPLE', 'BANANA', 'PINEAPPLE', 'ORANGE', 'MANGO', 'WATERMELON']


In [ ]:
new=[i.upper() for i in l]
print(new)

['APPLE', 'BANANA', 'PINEAPPLE', 'ORANGE', 'MANGO', 'WATERMELON']


In [ ]:
# write program to print sqrt of elements in below list and store it in new list
l=[2,4,9,18,25,40,36,72,81]
new=[i**0.5 for i in l]
print(new)

[1.4142135623730951, 2.0, 3.0, 4.242640687119285, 5.0, 6.324555320336759, 6.0, 8.48528137423857, 9.0]


In [ ]:
# Lambda Function
# lambda function is an anonymous function where it can take many arguments and single expression


In [ ]:
def f1():
  print("Hello")
f1()

Hello


In [ ]:
# Syntax: lambda arguments: single expression
# assign it to variable
a=lambda x,y: x+y
print(a(10,5))

15


In [ ]:
b=lambda x,y,z: (x+10,y+20,z+30)
print(b(2,3,4))

(12, 23, 34)


In [ ]:
# Note : Functions are first class objects --> a function can act like argument to the another function


In [ ]:
# We use lambda function when there is more argument and single expression

In [ ]:
# create function where it can print squar, cube, fourtime and sqrt of the numbers
def square(n):
  return n**2
def cube(n):
  return n**3
def four(n):
  return n**4
def sqrt(n):
  return n**0.5
print(square(5))
print(cube(2))
print(four(3))
print(sqrt(36))

25
8
81
6.0


In [ ]:
def power(n):
  return lambda a:a**n
square=power(2)
cube=power(3)
four=power(4)
sqrt=power(0.5)
print()

**10-07-2025 Practice**

In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3}
new_dict = my_dict.copy()
new_dict['d'] = 4
print(my_dict)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
print(dir(my_dict))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3}
result = my_dict.keys()
print(result)

dict_keys(['a', 'b', 'c'])


In [ ]:
list1=[1,-3,0.9,5.6]
[int(i) for i in list1]

[1, -3, 0, 5]

In [ ]:
set1 = {"Yellow", "Orange", "Black"}
set2 = {"Orange", "Blue", "Pink"}
set3 = set2.difference(set1)
print(set3)

{'Pink', 'Blue'}


In [ ]:
list1 = ['physics', 'chemistry', 1997, 2000]
print (list1[1][-1])

y


In [ ]:
def func(a,b):
    print(a-b)
a=4
b=9
func(a=b,b=a)

5


In [ ]:
L = [1, 3, 5, 7, 9]
print(L.pop(-3), end = ' ')

5 

In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3}
result = my_dict.get('b', 0)
print(result)

2


In [ ]:
nums = [1, 2, 3, 4, 5]
result = [x for x in nums if x % 2 == 0]
print(result)

[2, 4]


In [ ]:
set1 = {10, 20, 30, 40}
set2 = {50, 20, "10", 60}
set3 = set1.union(set2)
print(set3)

{40, 10, '10', 50, 20, 60, 30}


In [ ]:
numbers = [1, 2, 3, 4, 5]
result = [num * 2 for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
aList = [5, 10, 15, 25]
print(aList[::-2])


[25, 10]


In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3}
result = my_dict.setdefault('d', 4)
print(result)

4


In [ ]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}
dict1.update(dict2)
print(dict1)

{'a': 1, 'b': 3, 'c': 4}


In [ ]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

apple
banana
cherry


**28-07-2025**

In [ ]:
import xlrd

In [ ]:
loc ="C:\\Users\\gopis\\Downloads\\file_example_XLS_5000.xls"

**31-07-2025**

In [ ]:
#Numpy
import numpy as np

In [ ]:
# create array from
s1={1,2,3,4,5}
a=np.array(s1)
print(type(a))  #We can't convert set to array
print(a)

<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}


In [ ]:
t1=(1,2,3,4,5)
b=np.array(t1)
print(b)

[1 2 3 4 5]


In [ ]:
# 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)
# find no of rows and columns
print(a.shape)
# find dimensions
print(a.ndim)
# find no of elements
print(a.size)
# find data type
print(a.dtype)
# find itemsize means memory size
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [ ]:
# access elements from arrays
# syntax: array[row_index,col_index]
print(a[0])
print(a[1])
print(a[1,1])
print(a[0,2])

[1 2 3]
[4 5 6]
5
3


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# print 1st column in array
print(a[:,0])
# print 3rd column values
print(a[:,2])

[1 5 9]
[ 3  7 11]


In [ ]:
# access only particular line 10 11 12
print(a[2,1:4])
# print only 8 and 12
print(a[1:3,3])

[10 11 12]
[ 8 12]


In [ ]:
b=a[:,0]
for i in b:
  print(i)

1
5
9


In [ ]:
# Transpose
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Matrix multiplication_--> Dot product
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
c=np.dot(a,b)
print(c)
print(a@b)

[[13 16]
 [29 36]]
[[13 16]
 [29 36]]


In [ ]:
# Inverse
a=np.array([[1,2],[3,4]])
d=np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Diagonal Elements
e=np.diag(a)
print(e)

[1 4]


In [ ]:
# Note: Diagonal on vectors return a matrix
c=np.diag([1,4,5])
print(c)

[[1 0 0]
 [0 4 0]
 [0 0 5]]


In [ ]:
# Boolean Indexing
a=np.array([[1,2],[3,4],[5,6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(a>2)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print(a[a>2])

[3 4 5 6]


In [ ]:
l=[1,2,3,4,5,6]
print(l*2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a*2)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
# np.where(logic,True,False)
a=np.array([[1,2],[3,4],[5,6]])
# print numbers greater than 2 and less than number print it as -1
b=np.where(a>2,a,-1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
# To compute the indexes where the condition is true
c=np.array([10,19,20,30,41,50,61])
# get the index position of even numbers
even=np.argwhere(c%2==0).flatten()
print(even)

[0 2 3 5]


In [ ]:
even2=np.argwhere(a%2==0)
print(even2)

[[0 1]
 [1 1]
 [2 1]]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
even2=np.argwhere(a%2==0)
a_even=a[even2[:,0],even2[:,1]]
print(a_even)

[2 4 6]


**01-08-2025**

In [ ]:
# Reshaping of array
import numpy as np

In [ ]:
# create a range of array up to 10
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# create a range of array up 1 to 10
b=np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# convert array into 2 rows and 5 columns
c=b.reshape(2,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# convert array into 5 rows and 2 columns
d=b.reshape(5,2)
print(d)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# create a range of array from 1 to 6 and convert into 2 rows and 3 columns
e=np.arange(1,7)
print(e)
f=e.reshape(2,3)
print(f)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# np.newaxis--> Used to reshape the array
g=e[np.newaxis,:]
print(g)


[[1 2 3 4 5 6]]


In [ ]:
h=e[:,np.newaxis]
print(h)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
# concatenation
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concat((a,b),axis=0) #row wise
print(c)
d=np.concat((a,b),axis=1) #column wise
print(d)
e=np.concat((a,b),axis=None) #normal
print(e)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
# hstack--> Stack array adding in sequence horizentally
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
h=np.hstack((a,b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Vstack--> stack array adding sequence in vertically
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
v=np.vstack((a,b))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Broadcasting method--> It is a power mechanism tool that allows numpy to work with different arrays of different shapes when performing the arithmetic operations
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y=np.array([1,0,1])
z=x+y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# copying of an array
a=np.array([1,2,3])
b=a
b[0]=8
print(b)

[8 2 3]


In [ ]:
a=np.array([1,2,3])
b=a.copy() #using the copy command the original data will not effect or changes
b[0]=8
print(a)
print(b)

[1 2 3]
[8 2 3]


In [ ]:
# Generating arrays
# 1.Generate an array of zeros with 2 rows and 3 columns
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [ ]:
# 2.Generate an array of ones with 2 rows and 3 columns
b=np.ones((2,3))
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 3. Generate an array specific number with particular rows and columns
c=np.full((2,3),5)
print(c)

[[5 5 5]
 [5 5 5]]


In [ ]:
# Generate an identity matrix
d=np.eye(4)
print(d)
d1=np.identity(5)
print(d1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# np.linspace(start,end,no of partitions)--> splits the data into n equal parts
e=np.linspace(0,10,5)
print(e)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Generate random numbers
# Generate an array which is uniformaly distributed 0 to 1 with 3 rows and 2 column
a=np.random.random((3,2))
print(a)

[[0.33547538 0.62118616]
 [0.74023752 0.00309383]
 [0.42064322 0.23864954]]


In [ ]:
# generate an array of which is normally distribute with 1000 rows
b=np.random.randn(1000)
# print(b)
print(b.mean(),b.std())

0.02649556775570096 0.993652717965573


In [ ]:
# Generate an random integers
c=np.random.randint(3,10,size=(3,2))
print(c)

[[8 8]
 [8 5]
 [8 8]]


In [ ]:
import numpy as np

In [ ]:
# Solving the linear systems
a=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])
x=np.linalg.solve(a,b)
print(x)

[1500.  700.]


**05-08-2025**